namespace :geniverse do
  def homozygous_alleles(alleles = [])
    alleles.map{|a| ["a:#{a}","b:#{a}"]}.flatten.join(",")
  end

  desc "Setup the default geniverse cases and activities"
  task :setup => :environment do

    cases = []

    cases << { :id=>1,
      :name=>"Case 1",
      :order=>1,
      :introImageUrl=>"http://geniverse.dev.concord.org/resources/character_sketches.jpg"
    }

    cases.each do |c|
      myCase = Case.find_by_name(c[:name])
      if (myCase.nil?)
        puts "Creating new case: #{c[:name]}"
        Case.create!(c)
      else
        puts "Updating attributes of existing activity: #{c[:name]}"
        myCase.update_attributes!(c)
      end
    end

    activities = []

    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"List of pageTypes, aka Templates",
      :base_channel_name=>"pageType_List",
      :message=>"<h2>\r\nTemplates: \r\n</h2>\r\n<p>The following are the pageTypes in GV as of 1/1/11: <br>\r\nchromosomeTrainingPage, \r\nchromosomeBreedingPage, \r\n\r\nbreedingPage, \r\nbreedingPageMatch,\r\nbreedingPageGroup, \r\n\r\nmeiosisPage. \r\n\r\nThis activity (under this note) happens to be a chromosomeTrainingPage.\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/list",
      :max_users_in_room=>nil,
      :initial_alleles=>"",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: chromosomeTrainingPage",
      :base_channel_name=>"pageType_chromosomeTrainingPage",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/chromosomeTrainingPage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a', sex: 1, name: 'Starting Mother'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Template: chromosomeBreedingPage",
      :base_channel_name=>"pageType_chromosomeBreedingPage",
      :message=>"This is an example of the pageType called chromosomeBreedingPage.\t",
      :send_bred_dragons=>false,
      :static_genes=>"",
      :route=>"pagetype/reference/chromosomeBreedingPage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a', sex: 1, name: 'Starting Mother'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Template: chromosomeBreedingChallengePage",
      :base_channel_name=>"pageType_chromosomeBreedingChallengePage",
      :message=>"This is an example of the pageType called chromosomeBreedingChallengePage.\t",
      :send_bred_dragons=>false,
      :static_genes=>"",
      :route=>"pagetype/reference/chromosomeBreedingChallengePage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 1, name: 'Starter Female 1'},
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 0, name: 'Starter Male 1'}
      ] ] ];",
      :pageType=>"chromosomeBreedingChallengePage",
      :match_dragon_alleles=>"[ [ [
        {alleles:'#{homozygous_alleles(%w{T M w H C Fl Hl A1 B D rh})}', sex: 1, name: 'Match Female 1'},
        {alleles:'#{homozygous_alleles(%w{T M w h C Fl Hl A1 B D rh})}', sex: 0, name: 'Match Male 1'},
        {alleles:'#{homozygous_alleles(%w{T M w h C fl Hl A1 B D rh})}', sex: 1, name: 'Match Female 2'}
      ] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: breedingPage",
      :base_channel_name=>"pageType_breedingPage",
      :message=>"This is an example of the pageType called breedingPage.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/breedingPage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female 1'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:Fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Match Female 2'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Match Male 1'},{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Match Male 2'} ] ] ];",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>"[ [ [ {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female 1'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:Fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Match Female 2'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Match Male 1'},{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Match Male 2'} ] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: breedingChallengePage",
      :base_channel_name=>"pageType_breedingChallengePage",
      :message=>"This is an example of the pageType called breedingChallengePage.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/breedingChallengePage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 1, name: 'Starter Female 1'},
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 0, name: 'Starter Male 1'}
      ] ] ];",
      :pageType=>"breedingChallengePage",
      :match_dragon_alleles=>"[ [ [
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 1, name: 'Match Female 1'},
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 0, name: 'Match Male 1'},
        {alleles:'#{homozygous_alleles(%w{T M W H C Fl Hl A1 B D rh})}', sex: 1, name: 'Match Female 2'}
      ] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: breedingPageMatch",
      :base_channel_name=>"pageType_breedingPageMatch",
      :message=>"This is an example of the pageType called breedingPageMatch.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/breedingPageMatch",
      :max_users_in_room=>nil,
      :initial_alleles=>"",
      :pageType=>"breedingPageMatch",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: breedingPageGroup",
      :base_channel_name=>"pageType_breedingPageGroup",
      :message=>"This is an example of the pageType called breedingPageGroup.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/breedingPageGroup",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female 1'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:Fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Match Female 2'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Match Male 1'},{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Match Male 2'} ] ] ];",
      :pageType=>"breedingPageGroup",
      :match_dragon_alleles=>"[ [ [ {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female 1'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:Fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Match Female 2'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Match Male 1'},{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Match Male 2'} ] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: MeiosisPage",
      :base_channel_name=>"pageType_meiosisPage",
      :message=>"This is an example of the pageType called meiosis Page.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/meiosisPage",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:W,b:w,a:H,b:h,a:Fl,b:fl', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:w,b:W,a:h,b:H,a:fl,b:Fl', sex: 0, name: 'Starting Father'},{alleles:'a:m,b:m,a:B,b:b,a:d,b:d,a:c,b:c,a:A1,b:A1,a:w,b:w,a:h,b:H,a:fl,b:Fl', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: Placeholder Page 1",
      :base_channel_name=>"pageType_placeholder01",
      :message=>"This is a placeholder in case we want to insert another pageType/template page.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/placeholder/01",
      :max_users_in_room=>nil,
      :initial_alleles=>"",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>nil,
      :title=>"Template: Placeholder Page 2",
      :base_channel_name=>"pageType_placeholder02",
      :message=>"This is a placeholder in case we want to insert another pageType/template page.\r\n\r\nFor now, the text below remains in case it has useful info for formatting, etc.\r\n\r\n<p>\r\n<style type=\"text/css\"> a.finger { \tbackground-color: #FF00FF; } </style> Images have a magenta background color based on their class and inline CSS style element.<br/>  Long language-specific image URL works only on development laptops:<a href=\"#lab/caselog\" class=\"finger\"><img src=\"/static/lab/en/current/resources/images/backward.png\" alt=\"Back to Case Log\" width=\"49\" height=\"25\" border=\"0\"/></a><br/>  Simple relative image URL doesn't work<a href=\"#lab/caselog\" class=\"finger\"><img src=\"images/backward.png\" alt=\"Back to Case Log\" width=\"49\" height=\"25\" border=\"0\"/></a><br/>  Site-specific image URL works anywhere but will be broken if the site changes, so it's hard to maintain:<a href=\"#lab/caselog\" class=\"finger\"><img src=\"http://www.concord.org/sites/default/files/images/logos/cc/projects/geniverse-100.png\" alt=\"Back to Case Log\" border=\"0\"/></a><br/> ",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/placeholder/02",
      :max_users_in_room=>nil,
      :initial_alleles=>"",
      :pageType=>"breedingPageGroup",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training 1",
      :base_channel_name=>"heredityTraining1",
      :message=>"<h2>Welcome to the Training Lab</h2>\r\n<br>\r\n<p>1. Experiment with the pull-down menus and figure out how the traits of the drakes work. </p>\r\n\r\n<p>2. Determine a rule for each trait, and write it down in your Notepad (button at upper right). \r\n</p>\r\n\r\n<p>3. How many ways are there to make a drake with the same traits? Choose a drake and write a paper to explain how to make the drake in more than one way.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/training/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,a:D,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];\r\n\r\n//Both start as Nightwing: \r\n//Charcoal, Wings, Horns, Limbs, 5-armor, Flared tail.\r\n\r\n//Traits that students can select are:\r\n//Wings, Limbs, Tail.",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training 2",
      :base_channel_name=>"heredityTraining2",
      :message=>"<h2>Breeding Challenge</h2>\r\n<br /><br />\r\n1. Experiment with breeding drakes. <br /><br />\r\n\r\n2. Challenge: Match each target drake with an offspring drake by dragging the offspring to the target.\r\n<br />\r\nHint: Choose the parents' traits so you produce the target drake as one of the offspring. (You can create a new set of parents for each target drake).\r\n<br /><br />\r\n\r\n3. Can you match all three target drakes with one set of parents? \r\n\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"{'male': 'w,fl,hl,t'}",
      :route=>"heredity/training/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:w,b:W,a:Fl,b:fl,a:hl,b:hl,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];\r\n",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>"[ [ [ \r\n {alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:Fl,b:fl,a:hl,b:hl,a:w,b:w,a:T', sex: 1, name: 'match Mother'},\r\n {alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,a:fl,b:fl,a:hl,b:hl,a:T', sex: 1, name: 'match Mother2'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:w,b:w,a:fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'match Father'}\r\n] ] ];"}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training 3",
      :base_channel_name=>"heredityTraining3",
      :message=>"<h1>Challenges:</h1>\r\n\r\nUse the breeding pen and the statistics summaries to help you breed three different crosses that have offspring where:\r\n<ol><li>1. No offspring have wings and about half have forelimbs</li>\r\n<li>2. About half the offspring have wings, all have hindlimbs, and about half have flared tails</li>\r\n<li>3. Some, but not all, the offspring have hindlimbs, and some, but not all, have forelimbs</li></ol>\r\n\r\nFor each of the crosses above, <b>submit a paper to your teacher</b> describing how each cross can be made. <b>Find the link to your breeding record for each cross</b> beneath the breeding pen and submit this link as the evidence supporting your claim. In the reasoning section, describe why you think each cross works.\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"{'male': 'w,fl,hl,t'}",
      :route=>"heredity/training/case03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:a,b:a,a:B,b:B,a:D,b:D,a:W,b:W,a:Fl,b:Fl,a:hl,b:hl,a:T,b:t', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:a,b:a,a:B,a:D,a:w,b:w,a:fl,b:Fl,a:Hl,b:hl,a:t', sex: 0, name: 'Starting Father'} \r\n] ] ];",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'female': 'm, c, a, b, d, h, w, fl, hl, t', 'male': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training 4",
      :base_channel_name=>"heredityTraining4",
      :message=>"<h2>Challenge:</h2>\r\n<br />\r\n<b>The genes of the female drake are hidden. Your task is to determine what these hidden genes are. </b><br/><br />\r\n\r\n1. Make changes to the male drake and breed it with the female drake until you are certain you know what all the genes of the female are. <br/><br />\r\n\r\n2. Publish your results as a claim in a paper to your teacher. Be sure to support your claim with evidence in the form of screenshots and/or links to breeding records that prove your case.<br/><br />\r\n\r\n3. Return to this screen and create a male that enables you to know all of the female's traits with one click of the breed button.\r\n\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/training/case04",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:a,b:a,a:B,b:B,a:D,b:D,a:W,b:w,a:fl,b:fl,a:hl,b:Hl,a:t,b:T', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:a,b:a,a:B,a:D,a:w,b:W,a:Fl,b:Fl,a:Hl,b:hl,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];\r\n\r\n//this is a test comment\r\n",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Apprentice 1",
      :base_channel_name=>"heredityApprentice1",
      :message=>"<b>Using this screen</b>: Click on the Help button - <img width=\"18\" height=\"18\" src=\"https://img.skitch.com/20110117-t139558s16cdn5emcj877j5pjf.jpg\" />\r\n<br/><br/> \r\n<b>Challenge:</b> Cross drakes and observe the traits of the offspring. Look for patterns in the statistics tab that help you to explain the inheritance of each trait.\r\n<br/><br/> \r\n<b>Suggestions:</b>\r\n<ol>\r\n<li>* Concentrate on wings first. Find a male drake that has two different copies for this trait (such as wings/ no wings or no wings/wings). Breed this with the two different females and observe the results.</li>\r\n<li>* For each set of parents, publish a paper describing what you think happens with wings for that pairing and why you think so.</li>\r\n<li>* Choose another trait to examine. Conduct some breeding experiments until you think you understand how this trait is inherited from all combinations of parents.</li>\r\n</ol>\r\n\r\n<b>Publish a paper</b> describing how you could look at only the offspring of a pair of drakes and use what you see in the pen and the statistics to guess what the parent drakes' genes were.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/apprentice/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:w,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Starting Mother 2'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:W,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T', sex: 0, name: 'Starting Father'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:w,b:w,a:fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Starting Father 2'}\r\n] ] ];\r\n\r\n// Father 2 is the recessive test cross\r\n\r\n//fixed traits:  Charcoal, horns, armor \r\n//female:   a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Apprentice 2",
      :base_channel_name=>"heredityApprentice2",
      :message=>"<h2>Challenge:</h2>\r\n<br/>\r\nA new trait is varying -- some drakes have no horns! <br/><br/>\r\n\r\nUse what you know about breeding statistics and inheritance of different types of traits to describe as completely as you can the rules controlling how horns are inherited.<br/><br/>\r\n\r\n<b>Publish a paper stating your claim</b> about how the inheritance of horns works. Be sure to include screenshots and/or links to breeding records to support your claim, and to describe your reasoning completely.\r\n\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/apprentice/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles: 'a:m,b:m,a:h,b:H,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:Fl,b:Fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:Fl,b:Fl,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Starting Mother 2'},\r\n{alleles: 'a:m,b:m,a:H,b:H,a:C,b:C,a:A1,b:A1,a:B,a:D,a:w,b:w,a:Fl,b:Fl,a:Hl,b:Hl,a:T,b:T', sex: 0, name: 'Starting Father'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:w,b:w,a:fl,b:Fl,a:Hl,b:Hl,a:T,b:T', sex: 0, name: 'Starting Father 2'}\r\n] ] ];\r\n\r\n\r\n// all traits held constant except for horns\r\n\r\n//fixed traits:  Charcoal, armor \r\n//female:   a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Apprentice 3",
      :base_channel_name=>"heredityApprentice3",
      :message=>"<h2>Examining tails</h2>\r\n<br/>\r\nFlared tails are inherited a bit differently than other traits. Conduct some experiments, observe the offspring, and examine the statistics tab for clues to how tails are inherited. <br/><br/>\r\n\r\nWhen you think you have figured out a rule describing how this inheritance works, <b>publish a paper</b> stating your claim. If you have more than one claim to make, you may want to submit one paper for each claim. Be sure to back each claim up with evidence in the form of screenshots and links to breeding records, and to state your reasoning clearly! ",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/apprentice/case03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:Fl,b:Fl,a:Hl,b:Hl,a:T,b:t', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:Fl,b:Fl,a:Hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother 2'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:W,b:W,a:Fl,b:Fl,a:Hl,b:hl,a:T', sex: 0, name: 'Starting Father'},\r\n{alleles: 'a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D,a:W,b:W,a:Fl,b:Fl,a:Hl,b:Hl,a:t', sex: 0, name: 'Starting Father 2'}\r\n] ] ];\r\n\r\n\r\n\r\n// MOTHER 2 is the recessive test cross\r\n\r\n//fixed traits:  Charcoal, armor \r\n//female:   a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:h,b:h,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h, w, fl, hl, t'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Apprentice 4",
      :base_channel_name=>"heredityApprentice4",
      :message=>"<br />\r\n<h2>Challenge: Match this series of target drakes.</h2>\r\n<br />\r\n\r\n1. In order to match these target drakes, you will need to perform \"back-crosses\" by breeding offspring with parents and offspring with other offspring. \r\n<br /><br />\r\n\r\n2. Select offspring drakes and drag them to your stable to keep them aside for use in breeding. Once a drake is in your stable, you can drag it to replace a parent and then click the Breed button. If you no longer need a drake, you can remove it  by dragging it from the stable to the marketplace button.\r\n<br /><br />\r\n\r\n3. After you create the final target drake (the last one in the row of targets) publish a paper explaining how to use this drake to test the genotype of any other drake.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/apprentice/case04",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [\r\n\r\n[\r\n{alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 0, name: 'Nightwing Father'},\r\n{alleles:'a:m,b:m,a:W,b:w,a:H,b:h,a:C,b:C,a:Fl,b:fl,a:Hl,b:hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:t', sex: 1, name: 'Heterozygous Mother'}\r\n]\r\n\r\n] ];\r\n\r\n//Students are not given a recessive test cross - the target drakes are a series of increasingly recessive drakes, so they will breed it.\r\n// The presence of three parents is a bit of a red herring - no need for Nightwing female - should we have only two?\r\n// removed: {alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Nightwing Mother'}, \r\n\r\n//fixed traits:  Charcoal, armor \r\n//female:   a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>"[ [ [ \r\n{alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:Hl,b:hl,a:t,b:t', sex: 1, name: 'Match-Female-one trait recessive'},\r\n{alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Match Female-two traits recessive'},\r\n{alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:h,b:h,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Match Female-three traits recessive'},\r\n{alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:h,b:h,a:fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Match Male-all (varying) traits recessive'}\r\n] ] ];\r\n\r\n\r\n//\"Match Male-all (varying) traits recessive\" is the recessive test cross\r\n"}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Journeyman 1",
      :base_channel_name=>"heredityJourneyman1",
      :message=>"<h2>Challenge:</h2>\r\n\r\nExamine the drakes' armor and perform breeding experiments to determine how it is inherited. <br/><br/>\r\n\r\nSubmit your claims in the form of papers, including screenshots and breeding record links as evidence. Make sure to provide your reasoning for every claim.<br/>Be certain to submit papers to explain:\r\n<ol><li>* All the different types of armor you observe</li><li>* The rules that explain how <em>each type</em> is inherited</li></ol>",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/journeyman/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:a', sex: 1, name: 'Starting Mother'},\r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:A1', sex: 0, name: 'Starting Father'} \r\n] ] ];",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Journeyman 2",
      :base_channel_name=>"heredityJourneyman2",
      :message=>"<h2>Notice something different?</h2>\r\n<br><br>\r\n\r\n<b>Challenge: Determine how a new color is inherited in drakes.</b>\r\n<br><br>\r\n\r\nBreed and investigate the offspring to understand a new color gene. Make your claim in a paper - include evidence and explain your reasoning. How do the statistics support your claim?\r\n<br><br>\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/journeyman/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ \r\n[ \r\n{alleles:'a:m,b:M,a:D,b:d,a:A1,b:a,a:B,b:B,a:C,b:C,a:T,b:t', sex: 1, name: 'Starting Mother'}, \r\n{alleles:'a:m,b:m,a:D,a:A1,b:a,a:B,a:C,b:C,a:T', sex: 0, name: 'Starting Father'} \r\n],\r\n[ \r\n{alleles:'a:m,b:m,a:D,b:D,a:A1,b:a,a:B,b:B,a:C,b:C', sex: 1, name: 'Starting Mother'}, \r\n{alleles:'a:m,b:m,a:d,a:A1,b:a,a:B,a:C,b:C', sex: 0, name: 'Starting Father'} \r\n]\r\n] ];\r\n",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, b, d'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Journeyman 4",
      :base_channel_name=>"heredityJourneyman4",
      :message=>"<p>There are two more variations on genes in this screen. Can you find them? How are they inherited? You may need to exchange drakes and discuss to figure this out.</p>\r\n\r\n<p>As you learn more, discuss among your group in chat and author papers to back up your thinking. Remember to make claims, use breeding records and screenshots to support your evidence and give your reasoning.</p>",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/journeyman/case04",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles:'a:m,b:m,a:D,b:D,a:B,b:B,a:C,b:C,a:A1,b:A1,a:w,b:w,a:H,b:H,a:hl,b:hl,a:Fl,b:Fl,a:t,b:t', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:H,b:h,a:hl,b:hl,a:Fl,b:Fl,a:t', sex: 0, name: 'Starting Father'}, {alleles:'a:m,b:m,a:dl,b:d,a:B,b:B,a:C,b:C,a:A2,b:A2,a:w,b:w,a:h,b:h,a:hl,b:hl,a:Fl,b:fl,a:t,b:t', sex: 1, name: 'Starting Mother'} \r\n], [ \r\n{alleles:'a:m,b:m,a:D,b:dl,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:H,b:h,a:hl,b:hl,a:fl,b:fl,a:t,b:t', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:A2,b:A2,a:W,b:W,a:H,b:H,a:hl,b:hl,a:fl,b:fl,a:t', sex: 0, name: 'Starting Father'}, {alleles:'a:m,b:m,a:D,b:d,a:B,b:B,a:C,b:C,a:A1,b:A1,a:W,b:w,a:h,b:h,a:hl,b:hl,a:fl,b:fl,a:t,b:t', sex: 1, name: 'Starting Mother'} \r\n], [ \r\n{alleles:'a:m,b:m,a:d,b:dl,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:H,b:H,a:Hl,b:Hl,a:fl,b:fl,a:t,b:t', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:D,b:d,a:B,b:B,a:C,b:C,a:A1,b:A1,a:w,b:w,a:H,b:h,a:Hl,b:Hl,a:fl,b:fl,a:t', sex: 0, name: 'Starting Father'}, {alleles:'a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:A2,b:A2,a:w,b:w,a:h,b:h,a:Hl,b:hl,a:fl,b:fl,a:t,b:t', sex: 1, name: 'Starting Mother'} \r\n] ] ];",
      :pageType=>"breedingPageGroup",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'b'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity/Meoisis: Master 1",
      :base_channel_name=>"heredityMeiosisMaster1",
      :message=>"<b>Driving Questions:</b><br/>\r\n<ol><li>* Where is the d gene? The b gene?</li>\r\n<li>* How many new colors can you discover? How are they inherited?</li>\r\n<li>* What makes Frost drakes?</li></ol><br/>\r\n\r\n</b>Breeding Targets:</b><br/>\r\n<ol><li>* Breed a female Gold drake</li>\r\n<li>* Breed a female Argent drake with only one plate of armor </li></ol>",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity-meiosis/master/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:C,b:C,a:B,b:B,a:T,b:t,a:D,b:d', sex: 1, name: 'Starting Mother'},\r\n{alleles:'a:B,b:B,a:C,b:C', sex: 1, name: 'Starting Mother2'}, {alleles:'a:m,b:m,a:B,b:B,a:C,b:C,a:D,b:D,a:W,b:W,a:Fl,b:Fl,a:A1,b:A1,a:h,b:h,a:T,b:T,a:Hl,b:Hl', sex: 1, name: 'Nightwing Starting Mother'},\r\n{alleles:'a:m,b:m,a:B,b:B,a:C,b:C,a:D,b:D,a:W,b:W,a:Fl,b:Fl,a:A1,b:A1,a:h,b:h,a:T,b:T,a:Hl,b:Hl', sex: 0, name: 'Nightwing Starting Father'},\r\n ] ] ];",
      :pageType=>"breedingPageGroup",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Heredity/Meoisis: Master 2",
      :base_channel_name=>"heredityMeiosisMaster2",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity-meiosis/master/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:W,b:w,a:H,b:h,a:Fl,b:fl', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:w,b:W,a:h,b:H,a:fl,b:Fl', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"breedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d, h'}",
      :crossover_when_breeding=>false,
      :title=>"Meiosis: Apprentice 1",
      :base_channel_name=>"meiosisApprentice1",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"meiosis/apprentice/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:W,a:fl,b:Fl,a:hl,b:hl,a:T,b:t', sex: 1, name: 'Starting Mother'}, \r\n{alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T', sex: 0, name: 'Starting Father'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:Fl,a:hl,b:Hl,a:t', sex: 0, name: 'Match Male'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:fl,b:Fl,a:hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female'}\r\n] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>"[ [ [ \r\n{alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:Fl,a:hl,b:Hl,a:t', sex: 0, name: 'Match Male'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:fl,b:Fl,a:hl,b:Hl,a:T,b:T', sex: 1, name: 'Match Female'}\r\n] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Meiosis: Apprentice 2",
      :base_channel_name=>"meiosisApprentice2",
      :message=>"<p>Your goal in this case is to create four target drakes. To match each one, you will need to choose the correct parent drakes to breed and then choose the correct gametes from each one.</p>\r\n\r\n<p>The drakes shown below represent your target drakes. Once you have created a target drake take a screenshot of your drake and parents to confirm your success. Good luck!</p>\r\n\r\n<table width=\"100%\">\r\n<tr><td><img src=\"http://geniverse.dev.concord.org/resources/drakes/images/du_f_wing_allLimb_a0_fl_noHorn.png\" id=\"sc3806\" class=\"empty sc-regular-size\" width=\"100px\" height=\"100px\"style=\"left: 0px; right: 0px; top: 0px; bottom: 0px\"></td>\r\n<td><img src=\"http://geniverse.dev.concord.org/resources/drakes/images/du_f_noWing_allLimb_a0_fl_noHorn.png\" id=\"sc3813\" class=\"empty sc-regular-size\" width=\"100px\" height=\"100px\" style=\"left: 0px; right: 0px; top: 0px; bottom: 0px\"></td>\r\n<td><img src=\"http://geniverse.dev.concord.org/resources/drakes/images/du_m_wing_allLimb_a0_fl_noHorn.png\" id=\"sc3820\" class=\"empty sc-regular-size\" width=\"100px\" height=\"100px\"style=\"left: 0px; right: 0px; top: 0px; bottom: 0px\"></td>\r\n<td><img src=\"http://geniverse.dev.concord.org/resources/drakes/images/du_m_noWing_fore_a0_sh_noHorn.png\" id=\"sc3827\" class=\"empty sc-regular-size\" width=\"100px\" height=\"100px\"style=\"left: 0px; right: 0px; top: 0px; bottom: 0px\"></td>\r\n</tr></table>\r\n",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"meiosis/apprentice/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:fl,b:Fl,a:Hl,b:Hl,a:T,b:t', sex: 1, name: 'Starting Mother 1'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:Fl,a:Hl,b:hl,a:T,b:t', sex: 1, name: 'Starting Mother 2'}, {alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:W,b:w,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Starting Father 1'},{alleles:'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a,a:w,b:w,a:Fl,b:fl,a:Hl,b:Hl,a:T', sex: 0, name: 'Starting Father 2'}\r\n] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>false,
      :title=>"Meiosis: Apprentice 3",
      :base_channel_name=>"meiosisApprentice3",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"meiosis/apprentice/case03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:W,b:w,a:H,b:h,a:Fl,b:fl', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1,a:w,b:W,a:h,b:H,a:fl,b:Fl', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, b, d'}",
      :crossover_when_breeding=>false,
      :title=>"Meiosis: Journeyman 1",
      :base_channel_name=>"meiosisJourneyman1",
      :message=>"<p>Breed these two drakes and look carefully at the offspring. Do you notice any traits that always appear either apart or together?</p>\r\n\r\n<p>When you find two traits that always appear together, post a paper about this. Your claim should describe which two traits you think appear together. Post this in a paper in your personal blog and use an annotated screenshot as your evidence. Be sure to give a reason why you think this is occurring</p>  ",
      :send_bred_dragons=>nil,
      :static_genes=>"{'all': 'm, c, a,b, d,h,fl,d,hl,w,t'}",
      :route=>"meiosis/journeyman/case01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:h,a:fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Starting Father'},\r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:h,b:h,a:W,b:W,a:Fl,b:fl,a:hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother'}\r\n ] ] ];",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Meiosis: Journeyman 2",
      :base_channel_name=>"meiosisJourneyman2",
      :message=>"<p>Here are the drakes from the last example again. When you run meiosis on the mother, try using your mouse to click around on a chromosome and then choose a section of another chromosome to replace the selected portion with.</p>\r\n\r\n<p><b>Note:</b> The genes of both of the female parent drakes are exactly identical -- use them to reset the animation by dragging the unused female into the Mother slot when meiosis is done.</p>\r\n \r\n<p>Can you reproduce both of the target drakes?</p>",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"meiosis/journeyman/case02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:h,a:fl,b:fl,a:hl,b:hl,a:t', sex: 0, name: 'Starting Father'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:h,b:h,a:W,b:W,a:Fl,b:fl,a:hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:h,b:h,a:W,b:W,a:Fl,b:fl,a:hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother'} ] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:h,b:h,a:W,b:W,a:Fl,b:fl,a:hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother'},{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:h,b:h,a:W,b:W,a:fl,b:fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Starting Mother'} ] ] ];"}
    activities << {:hidden_genes=>"",
      :crossover_when_breeding=>true,
      :title=>"Meiosis: Journeyman 3",
      :base_channel_name=>"meiosisJourneyman3",
      :message=>"<p>Use what you have learned about recombination to match the two target drakes.</p>\r\n\r\n<p><b>Important:</b> When the father drake meiosis stops, <b>don't</b> recombine the father's chromosomes. Press play again to let the father's meiosis finish. Then concentrate on the chromosomes of the two mother drakes instead.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"meiosis/journeyman/case03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:h,a:fl,b:fl,a:hl,b:Hl,a:t', sex: 0, name: 'Starting Father'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:H,b:h,a:W,b:W,a:Fl,b:fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Starting Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:H,a:Fl,b:fl,a:hl,b:Hl,a:t,b:t', sex: 1, name: 'Starting Mother'} ] ] ];",
      :pageType=>"meiosisPage",
      :match_dragon_alleles=>"[ [ [ {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:h,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t', sex: 1, name: 'Target Mother'}, {alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:a,b:a,a:W,b:W,a:h,b:h,a:Fl,b:fl,a:Hl,b:hl,a:t,b:t', sex: 1, name: 'Starting Mother'} ] ] ];"}
    activities << {:hidden_genes=>"{'all': 'c, b, d, m'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Journeyman 3",
      :base_channel_name=>"heredityJourneyman3",
      :message=>"<h2>Interactive Colors</h2>\r\n<br />\r\n1. A third color appears in your parent pool. Some of your group members will already know how your new color works - and you will know how one of theirs works. \r\n<br /><br />\r\n\r\n2. Use the chat to find out what others in your group know about your new drake color.\r\n<br /><br />\r\n\r\n3. Exchange drakes through the chat so you have one of each color. Then breed the new colors against each other. Determine the rules of inheritance for this type of cross.\r\n<br /><br />\r\n\r\n4. For each new rule you discover about color, write a group paper, including evidence and reasoning to support your claim.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/journeyman/case03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father'}, \r\n{alleles:'a:m,b:m,a:B,b:B,a:D,b:D,a:C,b:C,a:A1,b:A1', sex: 1, name: 'Starting Mother'}, \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father2'} \r\n], [ \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father'}, \r\n{alleles:'a:M,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 1, name: 'Starting Mother'}, \r\n{alleles:'a:M,b:M,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father2'} \r\n], [ \r\n{alleles:'a:m,b:m,a:B,b:B,a:D,b:D,a:C,b:C,a:A1,b:A1', sex: 1, name: 'Starting Mother'},\r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father'}, \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father2'} \r\n], [ \r\n{alleles:'a:M,b:m,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 0, name: 'Starting Father'}, \r\n{alleles:'a:m,b:m,a:B,b:B,a:d,b:d,a:C,b:c,a:A1,b:A1', sex: 1, name: 'Starting Mother'}, \r\n{alleles:'a:M,b:M,a:B,b:B,a:d,b:d,a:C,b:C,a:A1,b:A1', sex: 1, name: 'Starting Mother2'} \r\n] ] ];\r\n",
      :pageType=>"breedingPageGroup",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'c, a, b, h, w, fl, hl, t'}",
      :crossover_when_breeding=>false,
      :title=>"Color Training Page",
      :base_channel_name=>"colorTrainingPage",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"pagetype/reference/color1",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [ {alleles: 'a:H,b:H,a:m,b:m,a:d,b:d,a:B,b:B,a:C,b:C,a:a,b:a', sex: 1, name: 'Starting Mother'}, {alleles: 'a:H,b:H,a:m,b:m,a:d,a:B,a:C,b:C,a:a,b:a', sex: 0, name: 'Starting Father'} ] ] ];",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'c, b, fl, hl, d, t'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training Test 1",
      :base_channel_name=>"heredityTrainingTest",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/training/test01",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,a:D,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];\r\n",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, d, fl, hl, t'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training Test 2",
      :base_channel_name=>"heredityTrainingTest2",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/training/test02",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,a:D,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'w, h, c, a, d, fl, hl, t'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Training Test 3",
      :base_channel_name=>"heredityTrainingTest3",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/training/test03",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,a:D,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];",
      :pageType=>"chromosomeTrainingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm, c, a, b, d'}",
      :crossover_when_breeding=>false,
      :title=>"Heredity: Training Test 4",
      :base_channel_name=>"heredityTrainingTest4",
      :message=>"",
      :send_bred_dragons=>nil,
      :static_genes=>"{'male': 'w,h,fl,hl,t'}",
      :route=>"heredity/training/test4",
      :max_users_in_room=>nil,
      :initial_alleles=>"[ [ [\r\n {alleles: 'a:m,b:m,a:W,b:W,a:H,b:H,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:Fl,b:FL,a:Hl,b:Hl,a:T,b:T', sex: 1, name: 'Starting Mother'}, \r\n {alleles: 'a:m,b:m,a:W,b:w,a:h,b:H,a:C,b:C,a:A1,b:A1,a:B,a:D,a:Fl,b:fl,a:Hl,b:hl,a:T', sex: 0, name: 'Starting Father'} \r\n] ] ];\r\n\r\n//for traits that are varying/selectable\r\n//male is STATIC heterozygous\r\n//female is SELECTABLE homozygous dominant",
      :pageType=>"chromosomeBreedingPage",
      :match_dragon_alleles=>""}
    activities << {:hidden_genes=>"{'all': 'm,c,a,b,d,hoxa1,rh'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Challenge 1",
      :base_channel_name=>"heredityChallenge1",
      :message=>"<br />\r\n<h2>Challenge: Match this series of target drakes.</h2>\r\n<br />\r\n\r\n1. In order to match these target drakes, you will need to perform \"back-crosses\" by breeding offspring with parents and offspring with other offspring. \r\n<br /><br />\r\n\r\n2. Select offspring drakes and drag them to your stable to keep them aside for use in breeding. Once a drake is in your stable, you can drag it to replace a parent and then click the Breed button. If you no longer need a drake, you can remove it  by dragging it from the stable to the marketplace button.\r\n<br /><br />\r\n\r\n3. After you create the final target drake (the last one in the row of targets) publish a paper explaining how to use this drake to test the genotype of any other drake.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/challenge/case01",
      :max_users_in_room=>nil,
      :threshold_three_stars=>1,
      :threshold_two_stars=>2,
      :initial_alleles=>%![[[
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:w,a:H,b:h,a:Fl,b:fl,a:Hl,b:hl,a:T,b:t,a:rh,b:rh', sex: 1, name: 'Heterozygous Mother'}
    ]]];!,
      :pageType=>"chromosomeChallengePage",
      :match_dragon_alleles=>%![ [ [
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:Hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match-Female-one trait recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match Female-two traits recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:h,b:h,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match Female-three traits recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:h,b:h,a:fl,b:fl,a:hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 0, name: 'Match Male-all (varying) traits recessive'}
    ] ] ];!}
    activities << {:hidden_genes=>"{'all': 'm,c,a,b,d,hoxa1,rh'}",
      :crossover_when_breeding=>true,
      :title=>"Heredity: Challenge 2",
      :base_channel_name=>"heredityChallenge2",
      :message=>"<br />\r\n<h2>Challenge: Match this series of target drakes.</h2>\r\n<br />\r\n\r\n1. In order to match these target drakes, you will need to perform \"back-crosses\" by breeding offspring with parents and offspring with other offspring. \r\n<br /><br />\r\n\r\n2. Select offspring drakes and drag them to your stable to keep them aside for use in breeding. Once a drake is in your stable, you can drag it to replace a parent and then click the Breed button. If you no longer need a drake, you can remove it  by dragging it from the stable to the marketplace button.\r\n<br /><br />\r\n\r\n3. After you create the final target drake (the last one in the row of targets) publish a paper explaining how to use this drake to test the genotype of any other drake.",
      :send_bred_dragons=>nil,
      :static_genes=>"",
      :route=>"heredity/challenge/case02",
      :threshold_three_stars=>8,
      :threshold_two_stars=>10,
      :max_users_in_room=>nil,
      :initial_alleles=>%![[[
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:w,a:H,b:h,a:Fl,b:fl,a:Hl,b:hl,a:T,b:t,a:rh,b:rh', sex: 1, name: 'Heterozygous Mother'}
    ]]];!,
      :pageType=>"chromosomeTripleChallengePage",
      :match_dragon_alleles=>%![ [ [
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:Hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match-Female-one trait recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:H,b:H,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match Female-two traits recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:W,b:W,a:h,b:h,a:Fl,b:Fl,a:hl,b:hl,a:t,b:t,a:rh,b:rh', sex: 1, name: 'Match Female-three traits recessive'},
    {alleles: 'a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D,a:w,b:w,a:h,b:h,a:fl,b:fl,a:Hl,b:Hl,a:t,b:t,a:rh,b:rh', sex: 0, name: 'Match Male-all (varying) traits recessive'}
    ] ] ];!}
    activities << { :myCase_id=>1,
      :myCaseOrder=>1,
      :title=>"Case 1: Challenge 1",
      :route=>"case01/activity01",
      :initial_alleles=>"[ [\r\n\r\n[\r\n{alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 0, name: 'Nightwing Father'},\r\n{alleles:'a:m,b:m,a:W,b:w,a:H,b:h,a:C,b:C,a:Fl,b:fl,a:Hl,b:hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:t', sex: 1, name: 'Heterozygous Mother'}\r\n]\r\n\r\n] ];\r\n\r\n//Students are not given a recessive test cross - the target drakes are a series of increasingly recessive drakes, so they will breed it.\r\n// The presence of three parents is a bit of a red herring - no need for Nightwing female - should we have only two?\r\n// removed: {alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Nightwing Mother'}, \r\n\r\n//fixed traits:  Charcoal, armor \r\n//female:   a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"chromosomeTrainingSinglePage",
      :match_dragon_alleles=>""}
    activities << { :myCase_id=>1,
      :myCaseOrder=>2,
      :title=>"Case 1: Challenge 2",
      :route=>"case01/activity02",
      :initial_alleles=>"[ [\r\n\r\n[\r\n{alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 0, name: 'Nightwing Father'},\r\n{alleles:'a:m,b:m,a:W,b:w,a:H,b:h,a:C,b:C,a:Fl,b:fl,a:Hl,b:hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:t', sex: 1, name: 'Heterozygous Mother'}\r\n]\r\n\r\n] ];\r\n\r\n//Students are not given a recessive test cross - the target drakes are a series of increasingly recessive drakes, so they will breed it.\r\n// The presence of three parents is a bit of a red herring - no need for Nightwing female - should we have only two?\r\n// removed: {alleles:'a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T', sex: 1, name: 'Nightwing Mother'}, \r\n\r\n//fixed traits:  Charcoal, armor \r\n//female:   a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,b:B,a:D,b:D\r\n//male:      a:m,b:m,a:C,b:C,a:A1,b:A1,a:B,a:D\r\n\r\n\r\n// Nightwing (for reference)\r\n//a:m,b:m,a:W,b:W,a:h,b:h,a:C,b:C,a:Fl,b:Fl,a:Hl,b:Hl,a:A1,b:A1,a:B,b:B,a:D,b:D,a:T,b:T\r\n",
      :pageType=>"chromosomeTrainingSinglePage",
      :match_dragon_alleles=>""}

    activities.each do |c|
      a = Activity.find_by_route(c[:route])
      if (a.nil?)
        puts "Creating new activity: #{c[:route]}"
        Activity.create!(c)
      else
        puts "Updating attributes of existing activity: #{c[:route]}"
        a.update_attributes!(c)
      end
    end
  end
end

Rake.application["db:setup".to_sym].enhance do
  Rake.application["geniverse:setup".to_sym].execute
end
