# This file is meant for development, in production we use a slightly different
# configuration
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: /bin/bash
    stdin_open: true
    tty: true

    # no ports are published, see below for details
    volumes:
      - .:/gpi
      - bundle:/bundle
volumes:
  bundle:
